Add Tamil (ta)
MuntashirAkon/SetEdit pull request #15
Opened 2022-10-01 10:55 UTC by Guru-25

Signed-off-by: Guru guru@duck.com

2022-10-01 11:54 UTC, MuntashirAkon requested changes
Filename is `.xml`, not `.yml`

2022-10-01 12:01 UTC, Guru-25 commented
> Filename is `.xml`, not `.yml`

sorry! changed.

2022-10-01 12:03 UTC, MuntashirAkon approved these changes

2022-10-05 15:47 UTC, merged

2025-01-12 08:45 UTC, Powerjuice900 approved these changes